on:
  push:
    branches:
      - main
      - feature-ci-*
  pull_request:
    branches:
      - main
      - feature-ci-*
jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      NCBI_API_KEY: ${{ secrets.NCBI_API_KEY }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          distribution: 'adopt-hotspot'
          java-version: '21'
          cache: 'gradle'
      - name: "Build"
        run: |
          gradle --build-cache assemble
      - name: "Test"
        run: |
          gradle check
