on:
  push:
    branches:
      - main
      - feature-ci-*
  pull_request:
    branches:
      - main
      - feature-ci-*
jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      NCBI_API_KEY: ${{ secrets.NCBI_API_KEY }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - uses: actions/setup-java@v5
        with:
          distribution: 'adopt-hotspot'
          java-version: '21'
          cache: 'gradle'
      - name: "Build"
        run: |
          gradle --build-cache assemble
      - name: "Test"
        run: |
          gradle check
