# This workflow performs a static analysis of your Kotlin source code using
# Detekt.
#
# Scans are triggered:
# 1. On every push to default and protected branches
# 2. On every Pull Request targeting the default branch
# 3. On a weekly schedule
# 4. Manually, on demand, via the "workflow_dispatch" event
#
# The workflow should work with no modifications, but you might like to use a
# later version of the Detekt CLI by modifing the $DETEKT_RELEASE_TAG
# environment variable.
name: Scan with Detekt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '44 2 * * 4'
  workflow_dispatch:

env:
  DETEKT_RELEASE_TAG: v1.15.0

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Get Detekt download URL
        id: detekt_info
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DETEKT_DOWNLOAD_URL=$(gh api graphql \
            --field tagName="$DETEKT_RELEASE_TAG" \
            --raw-field query="query getReleaseAssetDownloadUrl(\$tagName: String!) {
              repository(name: \"detekt\", owner: \"detekt\") {
                release(tagName: \$tagName) {
                  releaseAssets(name: \"detekt\", first: 1) {
                    nodes {
                      downloadUrl
                    }
                  }
                }
              }
            }" | jq --raw-output '.data.repository.release.releaseAssets.nodes[0].downloadUrl')

          echo "download_url=$DETEKT_DOWNLOAD_URL" >> "$GITHUB_OUTPUT"

          echo "download_url=$DETEKT_DOWNLOAD_URL" >> "$GITHUB_OUTPUT"

      - name: Setup Detekt
        run: |
          dest="$(mktemp -d)"
          curl --request GET \
            --url "${{ steps.detekt_info.outputs.download_url }}" \
            --silent \
            --location \
            --output "$dest/detekt"
          chmod a+x "$dest/detekt"
          echo "$dest" >> "$GITHUB_PATH"

      - name: Run Detekt
        continue-on-error: true
        run: |
          detekt --input "${{ github.workspace }}" --report "sarif:${{ github.workspace }}/detekt.sarif.json"

      - name: Make artifact location URIs relative
        continue-on-error: true
        run: |
          jq \
            --arg github_workspace "${{ github.workspace }}" \
            '. | ( .runs[].results[].locations[].physicalLocation.artifactLocation.uri |= if test($github_workspace) then .[($github_workspace | length + 1):] else . end )' \
            "${{ github.workspace }}/detekt.sarif.json" > "${{ github.workspace }}/detekt.sarif.json.tmp"
          mv "${{ github.workspace }}/detekt.sarif.json.tmp" "${{ github.workspace }}/detekt.sarif.json"

      - uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ${{ github.workspace }}/detekt.sarif.json
          checkout_path: ${{ github.workspace }}
